steps:
  - name: node:16
    entrypoint: yarn
    args: [ "install", "--force" ]

  - name: node:16
    entrypoint: yarn
    args: [ "run", "create-env" ]
    env:
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - 'API_URL=${_API_URL}'

  - name: "gcr.io/cloud-builders/gcloud"
    args: [ "app", "deploy", "--appyaml=infra/app.yaml" ]
