steps:
  - id: pull
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'docker pull gcr.io/$PROJECT_ID/frontend:latest || exit 0' ]

  - id: build
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--tag', 'gcr.io/$PROJECT_ID/frontend',
      '--cache-from', 'gcr.io/$PROJECT_ID/frontend:latest',
      '--build-arg', 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}',
      '.'
    ]

  - id: push
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/frontend:latest' ]

  - id: deploy
    name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'frontend',
      '--image', 'gcr.io/$PROJECT_ID/frontend:latest',
      '--region', 'europe-central2',
      '--allow-unauthenticated',
      '--update-env-vars', 'API_URL=${_API_URL}'
    ]
images:
  - 'gcr.io/$PROJECT_ID/frontend:latest'
